# Generated by Django 5.2.7 on 2025-10-17 17:03

import login.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
                ('objects', login.models.UsuarioManager()),
            ],
        ),
    ]
