# Generated by Django 5.2.7 on 2025-10-20 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_usuario_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='last_name',
        ),
    ]
