# Generated by Django 5.2.7 on 2025-11-27 01:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('cantidad', models.PositiveIntegerField()),
                ('costo', models.PositiveIntegerField()),
                ('stock_minimo', models.PositiveIntegerField()),
                ('unidad', models.CharField(choices=[('Unidad', 'Unidad'), ('Kilogramo', 'Kilogramo'), ('Gramo', 'Gramo'), ('Litro', 'Litro'), ('Mililitro', 'Mililitro'), ('Metro', 'Metro'), ('Centímetro', 'Centímetro'), ('Milímetro', 'Milímetro'), ('Paquete', 'Paquete'), ('Caja', 'Caja')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Negocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=1000)),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=12)),
                ('email', models.EmailField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Tema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='HorarioAtencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lunes_inicio', models.TimeField(blank=True, null=True)),
                ('lunes_fin', models.TimeField(blank=True, null=True)),
                ('martes_inicio', models.TimeField(blank=True, null=True)),
                ('martes_fin', models.TimeField(blank=True, null=True)),
                ('miercoles_inicio', models.TimeField(blank=True, null=True)),
                ('miercoles_fin', models.TimeField(blank=True, null=True)),
                ('jueves_inicio', models.TimeField(blank=True, null=True)),
                ('jueves_fin', models.TimeField(blank=True, null=True)),
                ('viernes_inicio', models.TimeField(blank=True, null=True)),
                ('viernes_fin', models.TimeField(blank=True, null=True)),
                ('sabado_inicio', models.TimeField(blank=True, null=True)),
                ('sabado_fin', models.TimeField(blank=True, null=True)),
                ('domingo_inicio', models.TimeField(blank=True, null=True)),
                ('domingo_fin', models.TimeField(blank=True, null=True)),
                ('negocio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='panel.negocio')),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.CharField(max_length=200)),
                ('icono', models.CharField(blank=True, max_length=50)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], max_length=20)),
                ('valor', models.PositiveIntegerField()),
                ('insumos', models.ManyToManyField(blank=True, related_name='servicios', to='panel.insumo')),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Cancelada', 'Cancelada'), ('Asistida', 'Asistida'), ('Ausente', 'Ausente')], default='Pendiente', max_length=20)),
                ('cancelado_por_usuario', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.servicio')),
            ],
        ),
    ]
