# Generated by Django 5.2.7 on 2025-11-03 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='hora',
            field=models.TimeField(default='9:00'),
            preserve_default=False,
        ),
    ]
