# Generated by Django 5.2.7 on 2025-11-03 21:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_alter_cita_hora'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorarioAtencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes'), ('Sábado', 'Sábado'), ('Domingo', 'Domingo')], max_length=50)),
                ('hora_apertura', models.TimeField()),
                ('hora_cierre', models.TimeField()),
                ('negocio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.negocio')),
            ],
        ),
    ]
