# Generated by Django 5.2.7 on 2025-11-03 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0003_horarioatencion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horarioatencion',
            name='dia',
        ),
        migrations.RemoveField(
            model_name='horarioatencion',
            name='hora_apertura',
        ),
        migrations.RemoveField(
            model_name='horarioatencion',
            name='hora_cierre',
        ),
        migrations.AddField(
            model_name='horarioatencion',
            name='domingo_fin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='horarioatencion',
            name='domingo_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='horarioatencion',
            name='jueves_fin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='horarioatencion',
            name='jueves_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='horarioatencion',
            name='lunes_fin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='horarioatencion',
            name='lunes_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='horarioatencion',
            name='martes_fin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='horarioatencion',
            name='martes_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='horarioatencion',
            name='miercoles_fin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='horarioatencion',
            name='miercoles_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='horarioatencion',
            name='sabado_fin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='horarioatencion',
            name='sabado_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='horarioatencion',
            name='viernes_fin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='horarioatencion',
            name='viernes_inicio',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='horarioatencion',
            name='negocio',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='panel.negocio'),
        ),
    ]
