# Generated by Django 5.2.7 on 2025-11-03 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0004_remove_horarioatencion_dia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horarioatencion',
            name='domingo_fin',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='horarioatencion',
            name='domingo_inicio',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='horarioatencion',
            name='jueves_fin',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='horarioatencion',
            name='jueves_inicio',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='horarioatencion',
            name='lunes_fin',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='horarioatencion',
            name='lunes_inicio',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='horarioatencion',
            name='martes_fin',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='horarioatencion',
            name='martes_inicio',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='horarioatencion',
            name='miercoles_fin',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='horarioatencion',
            name='miercoles_inicio',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='horarioatencion',
            name='sabado_fin',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='horarioatencion',
            name='sabado_inicio',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='horarioatencion',
            name='viernes_fin',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='horarioatencion',
            name='viernes_inicio',
            field=models.TimeField(),
        ),
    ]
