# Generated by Django 5.2.7 on 2025-11-06 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0006_alter_horarioatencion_domingo_fin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='valor',
            field=models.PositiveIntegerField(),
        ),
    ]
