# Generated by Django 5.2.7 on 2025-11-06 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0007_alter_servicio_valor'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='costo',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='insumo',
            name='unidad',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
