# Generated by Django 5.2.7 on 2025-11-06 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0009_alter_insumo_unidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='cantidad',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='costo',
            field=models.PositiveIntegerField(),
        ),
    ]
