# Generated by Django 5.2.7 on 2025-11-06 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0010_alter_insumo_cantidad_alter_insumo_costo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='unidad',
            field=models.CharField(choices=[('Unidad', 'Unidad'), ('Kilogramo', 'Kilogramo'), ('Gramo', 'Gramo'), ('Litro', 'Litro'), ('Mililitro', 'Mililitro'), ('Metro', 'Metro'), ('Centímetro', 'Centímetro'), ('Milímetro', 'Milímetro'), ('Paquete', 'Paquete'), ('Caja', 'Caja')], max_length=10),
        ),
    ]
