# Generated by Django 5.2.7 on 2025-11-07 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0011_alter_insumo_unidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Cancelada', 'Cancelada'), ('Asistida', 'Asistida'), ('Ausente', 'Ausente')], default='Pendiente'),
        ),
    ]
