# Generated by Django 5.2.7 on 2025-11-11 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0012_alter_cita_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='duracion',
        ),
    ]
