# Generated by Django 5.2.7 on 2025-11-23 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0013_remove_servicio_duracion'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='stock_minimo',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
