# Generated by Django 5.2.7 on 2025-11-23 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0014_insumo_stock_minimo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='stock_minimo',
            field=models.PositiveIntegerField(),
        ),
    ]
