# Generated by Django 5.2.7 on 2025-11-23 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0015_alter_insumo_stock_minimo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='cancelado_por_usuario',
            field=models.BooleanField(default=False),
        ),
    ]
