# Generated by Django 5.2.7 on 2025-11-24 23:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0016_cita_cancelado_por_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='cancelado_por_usuario',
        ),
        migrations.AddField(
            model_name='cita',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
