# Generated by Django 5.2.7 on 2025-11-24 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0017_remove_cita_cancelado_por_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='cancelado_por_usuario',
            field=models.BooleanField(default=False),
        ),
    ]
