# Generated by Django 5.2.7 on 2025-10-19 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagen',
            name='titulo',
            field=models.TextField(default='', max_length=50),
        ),
    ]
