# Generated by Django 5.2.7 on 2025-10-19 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_imagen_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='titulo',
            field=models.CharField(max_length=50),
        ),
    ]
