# Generated by Django 5.2.7 on 2025-10-20 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_alter_imagen_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagen',
            name='categoria',
            field=models.CharField(default=' ', max_length=50),
        ),
    ]
