# Generated by Django 5.2.7 on 2025-10-24 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0004_imagen_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='categoria',
            field=models.CharField(default='carrusel', max_length=50),
        ),
        migrations.AlterField(
            model_name='imagen',
            name='titulo',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
